/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Import {
  path: {
    name: string;
    folder: string;
    isDirectory: boolean;
    isFile: boolean;
    [k: string]: any;
  };
  file: {
    name: string;
    ext: string;
    folder: string;
    ctime: string;
    mtime: string;
    size: number;
    [k: string]: any;
  };
  [k: string]: any;
}
