// flow-typed signature: b24d933634448495b1b8b57a93969793
// flow-typed version: <<STUB>>/redux-saga-requests-axios_v^0.7.6/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-saga-requests-axios'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-saga-requests-axios' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-saga-requests-axios/dist/redux-saga-requests-axios' {
  declare module.exports: any;
}

declare module 'redux-saga-requests-axios/dist/redux-saga-requests-axios.min' {
  declare module.exports: any;
}

declare module 'redux-saga-requests-axios/es/axios-driver' {
  declare module.exports: any;
}

declare module 'redux-saga-requests-axios/es/index' {
  declare module.exports: any;
}

declare module 'redux-saga-requests-axios/lib/axios-driver' {
  declare module.exports: any;
}

declare module 'redux-saga-requests-axios/lib/index' {
  declare module.exports: any;
}

declare module 'redux-saga-requests-axios/src/axios-driver' {
  declare module.exports: any;
}

declare module 'redux-saga-requests-axios/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-saga-requests-axios/dist/redux-saga-requests-axios.js' {
  declare module.exports: $Exports<'redux-saga-requests-axios/dist/redux-saga-requests-axios'>;
}
declare module 'redux-saga-requests-axios/dist/redux-saga-requests-axios.min.js' {
  declare module.exports: $Exports<'redux-saga-requests-axios/dist/redux-saga-requests-axios.min'>;
}
declare module 'redux-saga-requests-axios/es/axios-driver.js' {
  declare module.exports: $Exports<'redux-saga-requests-axios/es/axios-driver'>;
}
declare module 'redux-saga-requests-axios/es/index.js' {
  declare module.exports: $Exports<'redux-saga-requests-axios/es/index'>;
}
declare module 'redux-saga-requests-axios/lib/axios-driver.js' {
  declare module.exports: $Exports<'redux-saga-requests-axios/lib/axios-driver'>;
}
declare module 'redux-saga-requests-axios/lib/index.js' {
  declare module.exports: $Exports<'redux-saga-requests-axios/lib/index'>;
}
declare module 'redux-saga-requests-axios/src/axios-driver.js' {
  declare module.exports: $Exports<'redux-saga-requests-axios/src/axios-driver'>;
}
declare module 'redux-saga-requests-axios/src/index.js' {
  declare module.exports: $Exports<'redux-saga-requests-axios/src/index'>;
}
