// flow-typed signature: cd7a6500a24d781ced5d35f0dc058a72
// flow-typed version: <<STUB>>/redux-saga-requests_v^0.23.0/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-saga-requests'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-saga-requests' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-saga-requests/dist/redux-saga-requests' {
  declare module.exports: any;
}

declare module 'redux-saga-requests/dist/redux-saga-requests.min' {
  declare module.exports: any;
}

declare module 'redux-saga-requests/es/actions' {
  declare module.exports: any;
}

declare module 'redux-saga-requests/es/constants' {
  declare module.exports: any;
}

declare module 'redux-saga-requests/es/helpers' {
  declare module.exports: any;
}

declare module 'redux-saga-requests/es/index' {
  declare module.exports: any;
}

declare module 'redux-saga-requests/es/middleware' {
  declare module.exports: any;
}

declare module 'redux-saga-requests/es/reducers' {
  declare module.exports: any;
}

declare module 'redux-saga-requests/es/sagas' {
  declare module.exports: any;
}

declare module 'redux-saga-requests/lib/actions' {
  declare module.exports: any;
}

declare module 'redux-saga-requests/lib/constants' {
  declare module.exports: any;
}

declare module 'redux-saga-requests/lib/helpers' {
  declare module.exports: any;
}

declare module 'redux-saga-requests/lib/index' {
  declare module.exports: any;
}

declare module 'redux-saga-requests/lib/middleware' {
  declare module.exports: any;
}

declare module 'redux-saga-requests/lib/reducers' {
  declare module.exports: any;
}

declare module 'redux-saga-requests/lib/sagas' {
  declare module.exports: any;
}

declare module 'redux-saga-requests/src/actions' {
  declare module.exports: any;
}

declare module 'redux-saga-requests/src/constants' {
  declare module.exports: any;
}

declare module 'redux-saga-requests/src/helpers' {
  declare module.exports: any;
}

declare module 'redux-saga-requests/src/index' {
  declare module.exports: any;
}

declare module 'redux-saga-requests/src/middleware' {
  declare module.exports: any;
}

declare module 'redux-saga-requests/src/reducers' {
  declare module.exports: any;
}

declare module 'redux-saga-requests/src/sagas' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-saga-requests/dist/redux-saga-requests.js' {
  declare module.exports: $Exports<'redux-saga-requests/dist/redux-saga-requests'>;
}
declare module 'redux-saga-requests/dist/redux-saga-requests.min.js' {
  declare module.exports: $Exports<'redux-saga-requests/dist/redux-saga-requests.min'>;
}
declare module 'redux-saga-requests/es/actions.js' {
  declare module.exports: $Exports<'redux-saga-requests/es/actions'>;
}
declare module 'redux-saga-requests/es/constants.js' {
  declare module.exports: $Exports<'redux-saga-requests/es/constants'>;
}
declare module 'redux-saga-requests/es/helpers.js' {
  declare module.exports: $Exports<'redux-saga-requests/es/helpers'>;
}
declare module 'redux-saga-requests/es/index.js' {
  declare module.exports: $Exports<'redux-saga-requests/es/index'>;
}
declare module 'redux-saga-requests/es/middleware.js' {
  declare module.exports: $Exports<'redux-saga-requests/es/middleware'>;
}
declare module 'redux-saga-requests/es/reducers.js' {
  declare module.exports: $Exports<'redux-saga-requests/es/reducers'>;
}
declare module 'redux-saga-requests/es/sagas.js' {
  declare module.exports: $Exports<'redux-saga-requests/es/sagas'>;
}
declare module 'redux-saga-requests/lib/actions.js' {
  declare module.exports: $Exports<'redux-saga-requests/lib/actions'>;
}
declare module 'redux-saga-requests/lib/constants.js' {
  declare module.exports: $Exports<'redux-saga-requests/lib/constants'>;
}
declare module 'redux-saga-requests/lib/helpers.js' {
  declare module.exports: $Exports<'redux-saga-requests/lib/helpers'>;
}
declare module 'redux-saga-requests/lib/index.js' {
  declare module.exports: $Exports<'redux-saga-requests/lib/index'>;
}
declare module 'redux-saga-requests/lib/middleware.js' {
  declare module.exports: $Exports<'redux-saga-requests/lib/middleware'>;
}
declare module 'redux-saga-requests/lib/reducers.js' {
  declare module.exports: $Exports<'redux-saga-requests/lib/reducers'>;
}
declare module 'redux-saga-requests/lib/sagas.js' {
  declare module.exports: $Exports<'redux-saga-requests/lib/sagas'>;
}
declare module 'redux-saga-requests/src/actions.js' {
  declare module.exports: $Exports<'redux-saga-requests/src/actions'>;
}
declare module 'redux-saga-requests/src/constants.js' {
  declare module.exports: $Exports<'redux-saga-requests/src/constants'>;
}
declare module 'redux-saga-requests/src/helpers.js' {
  declare module.exports: $Exports<'redux-saga-requests/src/helpers'>;
}
declare module 'redux-saga-requests/src/index.js' {
  declare module.exports: $Exports<'redux-saga-requests/src/index'>;
}
declare module 'redux-saga-requests/src/middleware.js' {
  declare module.exports: $Exports<'redux-saga-requests/src/middleware'>;
}
declare module 'redux-saga-requests/src/reducers.js' {
  declare module.exports: $Exports<'redux-saga-requests/src/reducers'>;
}
declare module 'redux-saga-requests/src/sagas.js' {
  declare module.exports: $Exports<'redux-saga-requests/src/sagas'>;
}
